### ISSUE TITLE
Usage with Django Rest Framework

### ISSUE THREAD

**Issue by rixx** [raphaelm/django-scopes#14]
I want to use a nested DRF serializer with a custom queryset specified up front, like this:

```
class SomethingSerializer(ModelSerializer):
    other = OtherSerializer(queryset=Other.objects.filter(is_deleted=False))
```

This crashes if you use django-scopes, because DRF evaluates field querysets at Django startup, unfortunately. Do you have an idea how to deal with this?

My current workaround involves a property on the base model, and using ``other = OtherSerializer(source='my_property')``, which feels overly complicated, but works.

**Comment by raphaelm** [comment]
I do use a pattern of

```
with scopes_disabled():
    class OrderFilter(FilterSet):
        email = django_filters.CharFilter(field_name='email', lookup_expr='iexact')
```

for FilterSets, which might work here or not, but I'm not sure if it's cleaner or less clean than the property approach. Another approach would be initializing the serializer field in ``__init__``

**Comment by utkuDAT** [comment]
I have the same problem and have no idea how to solve it.

**Comment by rixx** [comment]
Both the methods mentioned, Raphael's and mine, work, they are just a bit clumsy and feel hacky.

**Comment by utkuDAT** [comment]
@rixx What kind of property did you do? As I am new to python, I could not understand much.

**Comment by rixx** [comment]
On your model class, you would add a property containing the selected elements:

```python
class Something(models.Model):
    ...
    
    @property
    def my_property(self):
        return Other.objects.filter(...)
```

**Comment by harikvpy** [comment]
For anyone coming here late, you can try this. Replace the `SerializerMetaclass` with a custom version that disables scoping in its `__new__()` method. Then use this metaclass to define a custom `ModelSerializer` which can then be used as the base class for all the tenant sensitive model serializers.

```
from django_scope import scope_disabled

class ScopeDisabledSerializerMetaclass(SerializerMetaclass):
    def __new__(cls, name, bases, attrs):
        with scope_disabled():
            return super().__new__(cls, name, bases, attrs)


class MyModelSerializer(ModelSerializer, metaclass=ScopeDisabledSerializerMetaclass):
    pass
```
