### ISSUE TITLE
Correct use of SafeModelChoiceField and SafeModelChoiceField?

### ISSUE THREAD

**Issue by sangonzal** [raphaelm/django-scopes#35]
First, thanks for publising this library, it has been helpful as someone new to Django. I'm having some issues with scoping forms with foreign keys. 

Assume I have: 

```
class Company(models.model):
    tenant = models.ForeignKey()
    name = models.charField()

class Office(models.model):
    tenant = model.foreignKey()
    company = model.foreignKey()

class OfficeForm(forms.modelForm)
    class Meta:
        model = Office
        fields = ['tenant', 'company']
       field_classes = {
               'company': SafeModelChoiceField
        }
```

When I initialize OfficeForm, it's done in scope with the correct tenant. `with scope(tenant=tenant):`

My understanding is that we should use SafeModelChoiceField for the foreignKey in OfficeForm. The issue that I'm seeing is that the queryset for "company" in OfficeForm is always null. What I would expect instead is that it pulls the companies by filtering down the companies by using the tenantId in the scope. 

Is this expected? Are there any examples that I could take a look at with forms and foreignKeys?

**Comment by raphaelm** [comment]
SafeModelChoiceField is safe in the way that (a) it doesn't crash and (b) it never accidentally exposes too much data.

You still need to set a proper queryset, e.g.

```

class OfficeForm(forms.modelForm)
    class Meta:
        model = Office
        fields = ['tenant', 'company']
        field_classes = {
               'company': SafeModelChoiceField
        }
    def __init__(self, *args, **kwargs):
        super().__init__(self, *args, **kwargs)
        self.fields['company'] = Company.objects.filter(tenant=…some query…)
```
