### ISSUE TITLE
Similar work

### ISSUE THREAD

**Issue by CleitonDeLima** [raphaelm/django-scopes#9]
Hi,

I liked the proposal of this app. I like to see alternatives to this kind of problem.  
I have a system in production and little time and use a different approach to filter current tenant.  
I use a custom lookup to filter the tenant.  

Example:

```python
@Field.register_lookup
class CurrentTenant(models.Lookup):
    lookup_name = 'ct'

    def as_sql(self, compiler, connection):
        lhs, lhs_params = self.process_lhs(compiler, connection)
        tenant = get_current_tenant()  # received for middleware
        params = lhs_params

        return '%s = %s' % (lhs, str(tenant.id)), params


class TenantManager(models.Manager):
    queryset_class = models.QuerySet

    def get_queryset(self):
        return self.queryset_class(self.model, using=self._db).filter(
            tenant__id__ct=ANY_VALUE)
```

This approach has solved the problem with forms, ManyToMany or ForeignKey fields are filtered out.  
To run the tests I need this setting:  
```python
DATABASES['default']['TEST'] = {
    'NAME': 'test_database',
    'SERIALIZE': False
}
```
My inspiration for this was this [blog post](https://blog.sentry.io/2018/11/14/how-to-build-saas-application), as django's ORM is different from sqlalchemy, I believe it doesn't have a similar solution.  

As I have a few years of programming experience, I don't know if my approach is right. I thought about creating this issue to discuss it.

(Sorry my english, I'm brazilian 😬)

**Comment by raphaelm** [comment]
What you're doing there solves a different problem. django-scopes is about providing some a fallback safety when you *forget to add the filter() part*. Your code makes writing the filter part easier (in a weird way, if you ask me, I don't think lookups should depend on request state), so this kinda is a different problem ;)
